### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by vanbungkring** [mattberg/Ti.SlideMenu#1]
hi matt, how to change the window if i click on menu item 1 for example

i want if i click on Menu Item 1  the main window will open win_item1.js 

thanks before :) your code life safer :)

**Comment by mattberg** [comment]
this method doesn't really work well opening windows in that manner. it would work more with switching out full screen views.

**Comment by vanbungkring** [comment]
hi matt i made some change on your code,, i think tomorrow will finish
https://gist.github.com/3207599

main control is on menu.js

**Comment by vanbungkring** [comment]
but, thanks matt thats great code you made
